version: '3.8'

services:
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  # Database management interface (Adminer)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

